- modules/model_loader.py
many cloud providers are still using python v3.9 😐
> python v3.9 compatible

- modules/private_logger.py
> Fixed encoding when writing text files

- fooocus_version.py
- modules/patch.py
Reverts lllyasviel/Fooocus#361
Seems good enough after tests
> Reland "move text encoder to GPU"

- fooocus_version.py
- launch.py
- modules/expansion.py
- modules/patch.py
move expansion to managed device
> move expansion to managed device

- launch.py
- readme.md
Skip the xformers package installation if detecting AMD GPU. also add a section in readme.
> add support for AMD GPU on Linux

- modules/async_worker.py
- webui.py
> Added information about diffusion and total execution time (#463)

- wildcards/nationality
List made with chatGPT v4
Prompted:
`a list of all possible nationalities, one per line, no numerated, unique and never repeat. Just provide the list.`
Just a small and humble contribution 😋
> Add nationality.txt wildcard

- expansion_experiments.py
- fooocus_version.py
- modules/async_worker.py
- modules/expansion.py
> improve gpt2

- modules/private_logger.py
Minor optimization of logs. Added lazy loading of images.
> Added lazy loading of images in logs.html

- args_manager.py
- webui.py
Reverts lllyasviel/Fooocus#1315
> Revert "Disable Gradio analytics via argument"

- entry_with_update.py
Fixed grammar in entry_with_update.py
> fixed typo in entry_with_update.py

- javascript/zoom.js
I cleaned up the code that was left from auto1111 and is no longer needed, also made a couple of authoring changes and added the ability to cancel the last action on ctr+z.
Before you accept this PR, I'd like you to see if these changes fit, because what I've done is my vision, which may not fit you, and if I've done something that doesn't fit, I have no problem doing a rollback of that thing.
I added the ability to do undo action on Ctrl+z , tested on various scenarios, no problems with it. 
https://github.com/lllyasviel/Fooocus/assets/22278673/91a74ff3-4ced-41c0-be9c-2a1cc22c3ae6
1) Changed the zoom button from **Alt** to **Shift**. As I think it is much more convenient + no problem with firefox.
Originally it was **Shift** , but because someone could use horizontal scrolling, I had to …
> Code cleanup and small improvements for zoom in inpaint

- readme.md
Closes https://github.com/lllyasviel/Fooocus/issues/1747
Use consistent command with embedded python.exe
> update documentation for Windows (AMD)

- webui.py
Fixes #1879
Yep, it turned out to be that simple 😂
> Make the private log url path relative

- modules/inpaint_worker.py
Hi~ 
lllyasviel,
Fooocus is  an excellent work, it can generate beautiful images in both text2img and img2img tasks. However, I encountered a speed bottleneck with Fooocus when using it for inpainting/outpainting tasks. The issue was with the `morphological_open` function, which was originally written by PIL, This implementation tends to become slow as the size of the input image increased. To address this, I rewrote the function using OpenCV, achieving a 40x increase in speed for image sizes below 3K in inpainting/outpainting tasks.
The following table presents a comparation of the execution speeds for the modified of `morphological_open`, which was tested on Intel(R) Xeon(R) Gold 6271C CPU @ 2.60GHz CPU and V100 GPU
> [enhance]: use opencv to rewrite morphological_open(), achieve a 40x speed increase in morphological_open opporation

- modules/launch_util.py
added more logging to see what goes wrong, helps fix random errors.
> Upgrade requirements_met function

- modules/async_worker.py
add missing key for upscale fast 2x for private log.html, use correct parameter for output_format
> fix: adjust parameters for upscale fast 2x

- modules/async_worker.py
- modules/private_logger.py
As discussed in https://github.com/lllyasviel/Fooocus/pull/1940#issuecomment-1975123101
> feat: add metadata hint to history log

- modules/html.py
- webui.py
Fixes https://github.com/lllyasviel/Fooocus/discussions/2418
Before
After
> feat: adjust width of lora weight for firefox

- args_manager.py
- launch.py
- modules/config.py
- modules/launch_util.py
- modules/private_logger.py
This reverts commit 85e8aa8ce20dad2f87ebc4eafbc97707174ba64b, review in develop first
> Revert "feat: add config for temp path and temp path cleanup on launch (#1992)"

- modules/config.py
- modules/core.py
- presets/anime.json
- presets/default.json
- presets/lcm.json
- presets/realistic.json
- presets/sai.json
- webui.py
resolves https://github.com/lllyasviel/Fooocus/issues/2503
see https://github.com/lllyasviel/Fooocus/discussions/2479
add LoRA checkbox enable/disable handling to all necessary occurrences
> feat: allow to add disabled LoRAs in config

- Dockerfile
To match this: https://github.com/lllyasviel/Fooocus/pull/2517
Just tested on main branch with this change, and all works fine.
> Update xformers to 0.0.23 in Dockerfile

- modules/config.py
- modules/meta_parser.py
fixes https://github.com/lllyasviel/Fooocus/issues/2566
> fix: correctly set preset config and loras in meta parser

- modules/config.py
- modules/meta_parser.py
fixes https://github.com/lllyasviel/Fooocus/issues/2609
> load image number from preset

- modules/async_worker.py
fixes https://github.com/lllyasviel/Fooocus/issues/2599
> fix: use correct base dimensions for outpaint mask padding

- extras/vae_interpose.py
- fooocus_version.py
- launch.py
- modules/async_worker.py
- modules/config.py
- modules/meta_parser.py
- modules/util.py
- update_log.md
- improves on https://github.com/lllyasviel/Fooocus/pull/2702
- also implements changes of https://github.com/city96/SD-Latent-Interposer/blob/main/interposer.py
- model https://huggingface.co/city96/SD-Latent-Interposer/tree/main/v4.0
> feat: update interposer from v3.1 to v4.0

- javascript/script.js
- language/en.json
- webui.py
Fixes https://github.com/lllyasviel/Fooocus/issues/2716
Feedback about the button label would be appreciated.
> feat: add button to reconnect UI without having to reload the page

- entrypoint.sh
see https://github.com/lllyasviel/Fooocus/discussions/2836
adjusted for Linux (LF) again, previously Windows (CLRF)
> fix: use LF as line breaks for entrypoint.sh

- modules/async_worker.py
code should have been removed in https://github.com/lllyasviel/Fooocus/pull/2812/commits/a8a82647a9b064f94377b94dfba085ad02b11e86
> fix: remove leftover code for hyper-sd testing

- modules/async_worker.py
- modules/config.py
- modules/extra_utils.py
- modules/util.py
- tests/test_utils.py
- wildcards/.gitignore
- add performance loras to the end of the loras array
- allow multiple matches for each token
- optimize and extract method cleanup_prompt
> feat: inline lora optimisations

- javascript/localization.js
- javascript/script.js
- webui.py
use javascript code instead of python handling for updates for https://github.com/lllyasviel/Fooocus/pull/2590
> fix: use translation for aspect ratios label

- language/en.json
- modules/async_worker.py
- modules/config.py
- modules/default_pipeline.py
- modules/meta_parser.py
- webui.py
This reverts commit cc58fe52706a5a9ec75ad12f9643e19fe170e253.
There are issues in the implementation (see discussion https://github.com/lllyasviel/Fooocus/discussions/3003#discussioncomment-9563742) => rolling back for now until this has been sorted out to not block users from using Fooocus altogether.
> Revert "feat: add clip skip handling (#2999)"

- .github/workflows/build_container.yml
Relates to https://github.com/lllyasviel/Fooocus/pull/2805
@xynydev let's use tag "edge" on push to main.
> feat: build docker image on push to main branch

- webui.py
Closes https://github.com/lllyasviel/Fooocus/issues/3043
Closes https://github.com/lllyasviel/Fooocus/issues/3035
> fix: use default vae name instead of None on file refresh

- ldm_patched/contrib/external_custom_sampler.py
- modules/sample_hijack.py
Closes https://github.com/lllyasviel/Fooocus/issues/3060
sigmas can be calculated without having to load the whole model with model patcher
> fix: turbo scheduler loading issue

- Dockerfile
Closes https://github.com/lllyasviel/Fooocus/issues/3054
> fix: chown files directly at copy

- ldm_patched/k_diffusion/sampling.py
https://github.com/comfyanonymous/ComfyUI/pull/3370/commits/6fd91a8f006636bf0a2ddf306a280b6ca0591af7
> fix: correct sampling when gamma is 0

- modules/config.py
closes https://github.com/lllyasviel/Fooocus/issues/3144
set default_vae in any preset to use it
> feat: add vae to possible preset keys

- ldm_patched/k_diffusion/sampling.py
- ldm_patched/modules/samplers.py
- modules/flags.py
adapted code from [AUTOMATIC1111/stable-diffusion-webui#11850](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/11850)
> feat: add restart sampler

- modules/async_worker.py
- modules/sdxl_styles.py
fixes https://github.com/lllyasviel/Fooocus/issues/3367
> fix: add positive prompt in any case, even if styles didn't have a prompt placeholder

- language/en.json
- modules/config.py
- modules/flags.py
- webui.py
fixes https://github.com/lllyasviel/Fooocus/issues/2780
relates to https://github.com/lllyasviel/Fooocus/discussions/3407
> feat: add checkbox and config to disable updating selected styles when describing an image

- readme.md
see https://github.com/lllyasviel/Fooocus/issues/3836
> docs: remove link to SimpleSDXL

- readme.md
Quick for a path in the Readme.
The correct File is in the `Fooocus/` folder as correctly mentioned a couple of lines above
> Fix: Readme path
