- fooocus_version.py
- modules/patch.py
This reverts commit 7700276b5013ff6a4ce9776bfe6b6919326654b0.
This seems to influence result quality.
> Revert "move text encoder to GPU (#360)"

- build_launcher.py
When launching Foocus it's useful to be able to pass additional arguments to the launch script.
This change adds the the `%*` modifier at the end of the base command string so that we can do something like
```bash
./run.bat --listen
```
instead of modifying the batch file manually.
> Pass additional command line arguments to launch.py through run.bat scripts

- css/style.css
Hi, Fooocus is a very cool tool!
I've little improved the position of this tooltip.
Is this fix acceptable to this project?
Before:
After:
Thank you!
> Fix canvas tooltip position

- javascript/script.js
I noticed that the shortcut for a quick start with ctrl+enter would also cause an issue if hit again while the gernation had already started. It would click the (now hidden) generate button again in the background. One the first generation finishes the second would start off but the UI would not recognise it. 
This solves that by only clicking the button when visible as well as making the ctrl+enter shortcut stop the current generation allowing people to update their prompts faster if they dont like the current direction the previews are showing, or if they made a mistake.
> Fix generate shortcut bug and add interrupt shortcut

- css/style.css
Hi, glad to see that my work is present in this great interface.
I saw the issue #1427  and fixed the problem.
Also, if you agree, I can clean up `zoom.js` of unnecessary functions left over from auto1111.
> fix zooming on large-width images

- webui.py
When changing the prompt during generation currently the generate_button or load_parameter_button is displayed.
initial generate_button click:
change prompt:
This PR fixes this issue and does ...
- not display the generate_button on prompt changes during generation
- display the generate_button as non-interactive after clicking load_parameter_button during generation
> add workaround for changing prompt while generating

- modules/config.py
- webui.py
See https://github.com/lllyasviel/Fooocus/pull/1248
See https://github.com/lllyasviel/Fooocus/discussions/1511
Uses default_max_image_number as upper limit for default_image_number while keeping the default behaviour if not explicitely adjusted.
⚠️ Increasing default_image_number to a high value (depending on performance selection and GPU, roughly around > 5-10) may cause Gradio to lag heavily though.
Therefore best used in combination with https://github.com/lllyasviel/Fooocus/pull/1013.
> make max image number configurable

- args_manager.py
Currently the `--disable-in-browser` flag is not working because the [set_defaults](https://github.com/cocktailpeanut/Fooocus/blob/4ffe8738afab7571b81864f0c19dc31385fcec80/args_manager.py#L23-L27) line is overriding the `--disable-in-browser` handling that took place here: https://github.com/cocktailpeanut/Fooocus/blob/4ffe8738afab7571b81864f0c19dc31385fcec80/ldm_patched/modules/args_parser.py#L123-L124
To fix this, just add the same handling logic after the `set_defaults`.
> fix --disable-in-browser

- css/style.css
- javascript/script.js
Fixes #1816 
The overlay will be positioned on top or below the cursor depending on the position of the cursor in relation to the browser window to prevent it from being cut off.
Bug:
Fix:
Bottom:
Top:
> fix: prevent cutting off overlay

- .gitignore
This is for the [Linux (Using Python Venv)](https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#linux-using-python-venv) section in the readme which has instructions to create the `fooocus_env` virtual environment. I updated `.gitignore` instead of the name in the readme for users who might have already followed these instructions.
```bash
python3 -m venv fooocus_env
```
> chore: add venv mentioned in the readme to gitignore

- ldm_patched/contrib/external_canny.py
- ldm_patched/pfn/architecture/HAT.py
- ldm_patched/pfn/architecture/RRDB.py
There are multiple broken links in this project. Here is what I have fixed:
https://github.com/rlaphoenix/VSGAN/blob/master/vsgan/archs/ESRGAN.py --> https://github.com/rlaphoenix/VSGAN/blob/master/vsgan/archs/esrgan.py
https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/drop.py --> https://github.com/huggingface/pytorch-image-models/blob/main/timm/layers/drop.py
https://kornia-tutorials.readthedocs.io/en/latest/ --> https://kornia.readthedocs.io/en/latest/
This is an updated PR of #1007
These links where found with [link-inspector](https://github.com/justindhillon/link-inspector). If you find this PR useful, give the repo a ⭐
> Fix broken links

- launch.py
as it indirectly imports modules (like `PIL` or `cv2`) belonging to packages which may not yet be installed in the final correct versions.
Fixes #2155
> delay importing of modules.config

- modules/private_logger.py
Added `<!DOCTYPE html>` declaration
`<img/>` instead of `<img></img>`
`<br/>` instead of `</br>`
> Fixed mistakes in HTML generation

- modules/util.py
There is an issue in the file sorting, which has to do with the condition of the lambda. `os.sep` returns correctly, but the sorting of the else condition just appends to the end and beginning, which is wrong.
This PR implements sorting for files when walking as well as `topdown=False` to display subfolders first.
Closes https://github.com/lllyasviel/Fooocus/issues/1618
Relates to https://github.com/lllyasviel/Fooocus/pull/1517
before:
after:
> fix: correctly sort files, display deepest dir level first

- ldm_patched/modules/args_parser.py
- ldm_patched/modules/model_management.py
- readme.md
I have changed the `--always-cpu` argument to integer, if in the command line this argument is followed by a number greater than 0 it will be used in `torch.set_num_threads()` and override the default value.
On my 8 core AMD 7840U which supports 16 threads I noticed I got ~70% CPU utilization while running image generation. As i discovered PyTorch doesn't seem to be benefiting from SMT and sets the number of threads to the number of physical cores.
By increasing the number of threads from default 8 to 15 I received ~5% performance increase and 100% CPU utilization (see screenshots).
8 threads, 78.2 seconds/iteration
15 threads, 72.8% seconds/iteration
> Allow users specify number of threads when running on CPU via the extension to --always-cpu arg

- webui.py
Fixes https://github.com/lllyasviel/Fooocus/issues/907 and https://github.com/mashb1t/Fooocus/issues/18
Allows Gradio to serve outputs when folder has been changed in the config.
See 
- https://www.gradio.app/3.50.2/guides/sharing-your-app#security-and-file-access
- https://github.com/gradio-app/gradio/issues/4118
> fix: allow path_outputs to be outside of root dir

- modules/async_worker.py
previously skipped due to not being in np.ndarray format but string
> fix: add handling for filepaths to image grid

- modules/config.py
Closes https://github.com/lllyasviel/Fooocus/issues/2427
When default_loras is empty default_max_lora_number also has been set to 0, leading to not being able to see any loras.
With an additional check if default_loras is empty the default value for default_max_lora_number now has a fallback to 5.
> fix: add fallback value for default_max_lora_number when default_loras is empty

- modules/sdxl_styles.py
Closes https://github.com/lllyasviel/Fooocus/issues/2437
Matches now not only [[blue,red]], but also [[ (red:1.1), (blue:1.2) ]] and enables same seed checks for different prompt weight.
> feat: match anything in array syntax, not only words and whitespace

- modules/meta_parser.py
Fixes https://github.com/lllyasviel/Fooocus/issues/2446
fixes an issue with A1111 metadata scheme where resolution is a string
> fix: parse width and height as int when applying metadata

- webui.py
image grid is actually not an image here but a numpy array, as the grid isn't saved by default
> fix: do not attempt to remove non-existing image grid file

- .github/ISSUE_TEMPLATE/bug_report.yml
A few issues were popping up lately, which could have been solved by following steps in the troubleshooting guide.
This PR adds the link as checkbox to the bug report template again with the goal of better guiding users to fix their issues themselves.
> feat: add troubleshooting guide to bug report template again

- modules/config.py
- modules/flags.py
- modules/meta_parser.py
- modules/private_logger.py
- webui.py
Reasoning: 
1. we're already using jpeg to save a jpg file and should sync the filetype accordingly to support more features.
.jpg is just a compatible form for older OS which only support 3 characters for file extensions.
2. enums allow for less typos in strings and allow the actual value behind the enum option to be changed if needed.
- https://www.adobe.com/creativecloud/file-types/image/raster/jpeg-file.html
- https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#jpeg
- https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#jpeg-2000
> feat: use jpeg instead of jpg, use enums instead of strings

- modules/async_worker.py
- modules/config.py
- modules/flags.py
- presets/lightning.json
- webui.py
closes #2382, links to discussion https://github.com/lllyasviel/Fooocus/discussions/2318 & https://github.com/lllyasviel/Fooocus/discussions/2416
Based on https://huggingface.co/ByteDance/SDXL-Lightning/blob/main/sdxl_lightning_4step_lora.safetensors
Also read https://www.felixsanz.dev/articles/sdxl-lightning-quick-look-and-comparison#checkpoint-comparison (https://github.com/lllyasviel/Fooocus/discussions/2318#discussioncomment-8634972 @felixsanz).
Disables negative prompt for even faster generation with cfg = 1, even though it's capable of handling negative prompts with cfg > 1.
> feat: add performance sdxl lightning

- modules/config.py
- modules/sdxl_styles.py
- modules/util.py
- webui.py
Closes #2461 
Allows users to sort their wildcards in folders. Previously Fooocus would only search the base directory.
- Implements functionality for scanning subdirectories within the wildcards directory
- Adds a function for returning the first occurrence of a file within a directory tree
> feat: Scan wildcard subdirectories

- modules/async_worker.py
actually achieves the same result, stopping the task
> fix: use correct method call for interrupt_current_processing

- launch.py
fixes https://github.com/lllyasviel/Fooocus/issues/2513
```
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.1.0+cu121)
Python  3.10.11 (you have 3.10.9)
```
=> updating from 0.0.20 to 0.0.23
> fix: update incompatible xformers version

- modules/async_worker.py
Fixes https://github.com/lllyasviel/Fooocus/issues/2535
Seed shows up with rounding errors in metadata preview, parsing to string fixes it for preview.
No impoact except for displaying it, as https://github.com/lllyasviel/Fooocus/blob/main/modules/meta_parser.py#L132 already parses to int again.
> fix: parse seed as string to display correctly in metadata preview

- modules/async_worker.py
- modules/gradio_hijack.py
- webui.py
Fixes #2527. 
Displays an error message to the user that the image type is not supported and marks the task as finished to avoid hanging.
> fix: hang on unsupported image

- modules/meta_parser.py
Fixes https://github.com/lllyasviel/Fooocus/issues/2545
- write: don't write lora hashes to metadata when loras array is empty
- read: check if lora hashes string is present and not empty
> fix: correctly handle empty lora array in a1111 metadata log scheme

- presets/anime.json
prevents the prompt from getting overridden when switching presets in browser
> fix: remove positive prompt from anime prefix

- modules/config.py
- modules/meta_parser.py
- modules/util.py
fixes https://github.com/lllyasviel/Fooocus/issues/2600
> fix: add compatibility for LoRAs in a1111 metadata scheme

- docker.md
- fooocus_version.py
- launch.py
- ldm_patched/modules/args_parser.py
- modules/async_worker.py
- modules/config.py
- modules/meta_parser.py
- modules/model_loader.py
- modules/util.py
- readme.md
- update_log.md
As described https://github.com/lllyasviel/Fooocus/issues/2636 . 
Both env `HF_MIRROR` and startup argument `--hf-mirror` are supported to specify a mirror site to download huggingface files on fooocus runtime. Like : 
```
[System ARGV] ['launch.py', '--listen', '--hf-mirror=https://hf-mirror.com']
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Fooocus version: 2.3.1
... 
[Fooocus] Downloading upscale models ...
[Fooocus] Downloading inpainter ...
Downloading: "https://hf-mirror.com/lllyasviel/fooocus_inpaint/resolve/main/fooocus_inpaint_head.pth" to /content/data/models/inpaint/fooocus_inpaint_head.pth
100%|██████████| 51.4k/51.4k [00:00<00:00, 19.0MB/s]
Downloading: "https://hf-mirror.com/lllyasviel/fooocus_inpaint/resolve/main/inpaint_v26.fooocus.patch" to …
```
> feat:support download huggingface files from a  mirror site

- entrypoint.sh
Closes https://github.com/lllyasviel/Fooocus/issues/2863
https://github.com/lllyasviel/Fooocus/discussions/2836 was a false alarm, worked as intended before. Sorry for the fuzz.
This reverts commit d16a54edd69f82158ae7ffe5669618db33a01ac7.
> Revert "fix: use LF as line breaks for Docker entrypoint.sh (#2843)"

- entrypoint.sh
- language/en.json
- ldm_patched/modules/sd.py
- modules/async_worker.py
- modules/config.py
- modules/core.py
- modules/default_pipeline.py
- modules/flags.py
- modules/meta_parser.py
- modules/util.py
- webui.py
closes https://github.com/lllyasviel/Fooocus/issues/1840 (@E2GO fyi)
as discussed in https://github.com/lllyasviel/Fooocus/discussions/2861 (@ILikeToasters fyi)
Adds a dropdown for model VAE, which is especially handy when the base model doesn't have one baked in.
Upload VAEs to the already existing models/vae folder.
IMPORTANT: not models/vae_approx, which is used for the preview of intermediate step images with fixed VAE 
Open TODO's:
Tested with model [Mohawk](https://civitai.com/models/144952?modelVersionId=286100) (any other model with no VAE baked in will work for testing too)
Before:
washed out look, desaturated
<details><summary>Details</summary>
<p>
(EDIT screenshot with different model, see exact resulting image below)
</p>
</details> 
After:
selected VAE is applied, colorful …
> Add VAE select

- modules/ui_gradio_extensions.py
One `<meta>` tag on the main page had an invalid closing `</meta>` tag, changed it to `<meta />` to match the rest of the page.
> fix: do not close meta tag in HTML header

- ldm_patched/contrib/external_align_your_steps.py
- modules/flags.py
- modules/sample_hijack.py
https://github.com/comfyanonymous/ComfyUI/blob/794a357f7a4bd40c6e2dafab9d93142be9933a56/comfy_extras/nodes_align_your_steps.py https://research.nvidia.com/labs/toronto-ai/AlignYourSteps/howto.html
> feat: add align your steps scheduler

- modules/async_worker.py
- modules/config.py
- modules/flags.py
Hyper-SD: https://huggingface.co/ByteDance/Hyper-SD
LoRA: https://huggingface.co/ByteDance/Hyper-SD/blob/main/Hyper-SDXL-4steps-lora.safetensors
Discussion: https://github.com/lllyasviel/Fooocus/discussions/2794
Poll: https://github.com/lllyasviel/Fooocus/discussions/2813
WIP - sampler and scheduler are not yet final, currently using ddim and sgm_uniform (recommended by ByteDance)
> feat: add performance hyper-sd based on 4step LoRA

- extras/censor.py
- modules/async_worker.py
NSFW censoring now follows general Fooocus model management principles (improved loading and offloading, GPU now handles the processing if possible.)
Includes code optimisations for reusability.
1 shot values, no avg, tested with RTX 3080 and DDR4 RAM:
- only RAM 240.42 seconds (before adjustments)
- only GPU 216.37 seconds
- moving model between RAM / GPU 215.90 seconds (basically same as GPU only)
> feat: optimize model management of nsfw image censoring

- css/style.css
- modules/async_worker.py
- modules/flags.py
- modules/util.py
- align progress bar vertically to the middle
- set status text to fixed width
- remove ordinals, use image counter instead
=> visual decluttering, prevents progress bar from popping back, increase readability of progress
> feat: progress bar improvements

- .github/CODEOWNERS
As @lllyasviel has been inactive for ~4 months now (since 2024-01-28, see last commits in https://github.com/lllyasviel/Fooocus/commits/main/?author=lllyasviel) it's just more practical to maintain the code effectively when I'm also the one pinged on new PRs / issues in general, especially when being the only active collaborator / maintainer on this repository.
@lllyasviel if you read this, your feedback is more than welcome. I'm planning to publish 2.4.0-RC1 today, so I'd like to merge this adjustment in 2.4.0 (non-rc).
> feat: change code owner from @lllyasviel to @mashb1t

- css/style.css
- webui.py
relates to https://github.com/lllyasviel/Fooocus/issues/2660
Workaround as tool color-sketch applies changes directly to the image canvas and not the mask canvas.
Color picker is not correctly implemented in Gradio 3.41.2 => does always get displayed as separate containers and not merged with other elements.
> feat: add inpaint brush color picker

- language/en.json
- modules/async_worker.py
- modules/config.py
- modules/default_pipeline.py
- modules/meta_parser.py
- webui.py
Inspired by https://github.com/MoonRide303/Fooocus-MRE/blob/e4415d1d983ffaaeeaacdc23489a335c078641fe/modules/default_pipeline.py#L197-L203
includes
- metadata handling (when set > 1)
- history log (when set > 1)
- preset switching
- fallback to default config value
Civitai.com handling:
> feat: add clip skip handling

- language/en.json
- modules/async_worker.py
- modules/config.py
- modules/default_pipeline.py
- modules/flags.py
- modules/meta_parser.py
- webui.py
see https://github.com/lllyasviel/Fooocus/discussions/3003#discussioncomment-9563742
Background: Fooocus uses clip skip 2 by default, but the variable is called layer_idx and it works similar to ComfyUI, where skipped layers are counted down from -1 (no layer skipped) to infinity (set to last layer when loaded). Values > 12 are possible, they will somewhen reach a maximum of available layers, but are currently limited to 12 to prevent users from creating bad results.
The issues has been resolved by setting clip_skip to 2 by default instead of 1 and renaming the label to indicate the recommended default value.
Code references:
https://github.com/lllyasviel/Fooocus/blob/e8d88d3e250e541c6daf99d6ef734e8dc3cfdc7f/ldm_patched/modules/sdxl_clip.py#L9 …
> fix: adjust clip skip default value from 1 to 2

- javascript/localization.js
Adds type check for undefined, fall back to label "Aspect Ratios".
> fix: do not set textContent on undefined when no translation was given

- modules/async_worker.py
- modules/config.py
- modules/flags.py
- modules/meta_parser.py
- modules/private_logger.py
- modules/util.py
- tests/test_utils.py
- webui.py
Closes https://github.com/lllyasviel/Fooocus/issues/3010
Adds various optimizations for metadata and LoRA handling for performance LoRAs (goal: not apply them twice when loading metadata again)
> feat: optimize performance lora filtering in metadata

- webui.py
disable intermediate results for all performances with restricted features
make disable_intermediate_results interactive again even if performance has restricted features users who want to disable this option should be able to do so, even if performance will be impacted
> feat: rework intermediate image display for restricted performances

- css/style.css
- javascript/viewer.js
- webui.py
Closes https://github.com/lllyasviel/Fooocus/discussions/3063
Now always shows the full prompt, no fixed height anymore and no scrolling without scroll bar.
> feat: make textboxes (incl. positive prompt) resizable again

- modules/config.py
- modules/extra_utils.py
- tests/test_extra_utils.py
enables config overrides of boolean values as they are potentially provided as strings by docker / docker compose
> feat: parse env var strings to expected config value types

- presets/playground_v2.5.json
- reduce cfg of from 3 to 2 to prevent oversaturation
- remove style presets Fooocus Enhance and Fooocus Sharp
> feat: adjust playground_v2.5 preset

- modules/flags.py
- modules/meta_parser.py
fixes a bug where when lightning and hyper-sd have the same IntEnum value lightning is always used instead of hyper-sd
> apply performance from metadata

- modules/flags.py
adds method Performance.values(), fixes https://github.com/lllyasviel/Fooocus/commit/3e453501f702a7d419dd4b4a2067ab6a7daca495
> hotfix: add missing method in performance enum

- modules/meta_parser.py
- webui.py
fixes https://github.com/mashb1t/Fooocus/issues/57
allow metadata reading from jpeg and webp again
see https://github.com/mashb1t/Fooocus/discussions/56#discussioncomment-10077227
also massively improves metadata read speed
> fix: allow reading of metadata from jpeg, jpg and webp again

- modules/async_worker.py
fixes https://github.com/lllyasviel/Fooocus/issues/3327
as discussed in https://github.com/lllyasviel/Fooocus/discussions/3323
add missing inheritance for EarlyReturnException from BaseException to correctly throw and catch
> fix: correctly debug preprocessor again

- .github/ISSUE_TEMPLATE/bug_report.yml
- modules/async_worker.py
- modules/config.py
- modules/flags.py
- webui.py
As discussed in https://github.com/lllyasviel/Fooocus/discussions/3370 / https://github.com/lllyasviel/Fooocus/discussions/3380
New settings for config.txt (only preset support when starting with `--preset`, not when switching):
- default_image_prompt_checkbox
- default_enhance_checkbox
- default_developer_debug_mode_checkbox
- default_image_prompt_advanced_checkbox
- default_selected_image_input_tab_id
- default_uov_method
- default_controlnet_image_count
- default_ip_image_{default_controlnet_image_count} 
- default_ip_stop_at_{default_controlnet_image_count} 
- default_ip_weight_{default_controlnet_image_count} 
- default_ip_types_{default_controlnet_image_count} 
- default_inpaint_advanced_masking_checkbox
- default_invert_mask_checkbox
> feat: extend configs

- extras/BLIP/models/blip.py
- extras/BLIP/models/blip_nlvr.py
- extras/facexlib/detection/__init__.py
- extras/facexlib/parsing/__init__.py
- extras/ip_adapter.py
- ldm_patched/ldm/modules/encoders/noise_aug_modules.py
- ldm_patched/modules/sd1_clip.py
- ldm_patched/pfn/architecture/face/codeformer.py
- ldm_patched/pfn/architecture/face/gfpgan_bilinear_arch.py
- ldm_patched/pfn/architecture/face/gfpganv1_arch.py
- ldm_patched/pfn/architecture/face/gfpganv1_clean_arch.py
- modules/core.py
- modules/inpaint_worker.py
- modules/upscaler.py
`torch.load` without `weights_only` parameter is unsafe. Explicitly set `weights_only` to False only if you trust the data you load and full pickle functionality is needed, otherwise set `weights_only=True`.
If `weights_only=True` doesn't work for some cases, then explicit `weights_only=False` should be used.
Found with https://github.com/pytorch-labs/torchfix/
> Use weights_only for loading

- launch.py
Fixes https://github.com/lllyasviel/Fooocus/issues/3492
> fix: check all checkpoint dirs instead of only the first one for models

- modules/async_worker.py
sort images starts from index <images_to_enhance_count>, which is 1 if enhance_input_image has been provided
> hotfix: yield enhance_input_image to correctly preview debug masks

- launch.py
fixes https://github.com/lllyasviel/Fooocus/issues/3502
only import exactly when needed to resolve gradio issue on colab
> fix: resolve colab unsupported image type issue
